services:
  mail-client:
    image: roundcube/roundcubemail:1.6.11-apache
    depends_on:
      - mail-server
    volumes:
      - ./roundcube/db/sqlite:/var/roundcube/db
    ports:
      - 9002:80
    networks:
      - main
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=mail-server
      - ROUNDCUBEMAIL_SMTP_SERVER=mail-server
  mail-server:
    build:
      context: .
      args:
        IMAP_USER: ${IMAP_USER}
        LOCAL_IMAP_PASSWORD: ${LOCAL_IMAP_PASSWORD}
    hostname: mail-server
    networks:
      - main
    environment:
      OVERRIDE_HOSTNAME: mail-server.de
      ENABLE_QUOTAS: 0
    volumes:
      - "./data:/var/mail"
networks:
  main:
    name: mail-backup-network
    external: true